//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonDock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvalonDock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatikus elrejtés.
        /// </summary>
        public static string AutoHideCommand {
            get {
                return ResourceManager.GetString("AutoHideCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindet bezár kivéve ezt.
        /// </summary>
        public static string CloseAllButThisCommand {
            get {
                return ResourceManager.GetString("CloseAllButThisCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezár.
        /// </summary>
        public static string CloseCommand {
            get {
                return ResourceManager.GetString("CloseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elrejtés.
        /// </summary>
        public static string HideCommand {
            get {
                return ResourceManager.GetString("HideCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új vízszintes térosztó.
        /// </summary>
        public static string NewHorizontalTabGroupCommand {
            get {
                return ResourceManager.GetString("NewHorizontalTabGroupCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új függőleges térosztó.
        /// </summary>
        public static string NewVerticalTabGroupCommand {
            get {
                return ResourceManager.GetString("NewVerticalTabGroupCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        public static string ShowOptionsCommand {
            get {
                return ResourceManager.GetString("ShowOptionsCommand", resourceCulture);
            }
        }
    }
}
