//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neurotoxin.Godspeed.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neurotoxin.Godspeed.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Author: Mercenary/Neurotoxin&lt;br/&gt;Homepage: &lt;a href=&quot;http://godspeed.codeplex.com&quot; target=&quot;_blank&quot;&gt;http://godspeed.codeplex.com&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.&lt;/p&gt;
        ///&lt;p&gt;This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warrant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous login.
        /// </summary>
        internal static string AnonymousLogin {
            get {
                return ResourceManager.GetString("AnonymousLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache expiration.
        /// </summary>
        internal static string CacheExpiration {
            get {
                return ResourceManager.GetString("CacheExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Occupied Space.
        /// </summary>
        internal static string CalculateOccupiedSpace {
            get {
                return ResourceManager.GetString("CalculateOccupiedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for newer version on startup.
        /// </summary>
        internal static string CheckForNewerVersionOnStartup {
            get {
                return ResourceManager.GetString("CheckForNewerVersionOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        internal static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string CommandsMenu {
            get {
                return ResourceManager.GetString("CommandsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection details.
        /// </summary>
        internal static string ConnectionDetails {
            get {
                return ResourceManager.GetString("ConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost.
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection name.
        /// </summary>
        internal static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content recognition.
        /// </summary>
        internal static string ContentRecognition {
            get {
                return ResourceManager.GetString("ContentRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with regular (indirect) copy.
        /// </summary>
        internal static string ContinueWithIndirectCopy {
            get {
                return ResourceManager.GetString("ContinueWithIndirectCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5 Copy.
        /// </summary>
        internal static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy TitleID to Clipboard.
        /// </summary>
        internal static string CopyTitleIDtoClipboard {
            get {
                return ResourceManager.GetString("CopyTitleIDtoClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8 Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Custom Window Chrome.
        /// </summary>
        internal static string DisableCustomWindowChrome {
            get {
                return ResourceManager.GetString("DisableCustomWindowChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this message again.
        /// </summary>
        internal static string DontShowThisMessageAgain {
            get {
                return ResourceManager.GetString("DontShowThisMessageAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reconnect?.
        /// </summary>
        internal static string DoYouWantToReconnect {
            get {
                return ResourceManager.GetString("DoYouWantToReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4 Edit.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FilesMenu {
            get {
                return ResourceManager.GetString("FilesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Structure.
        /// </summary>
        internal static string FileStructure {
            get {
                return ResourceManager.GetString("FileStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Log.
        /// </summary>
        internal static string FTPLog {
            get {
                return ResourceManager.GetString("FTPLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate cache if source changes.
        /// </summary>
        internal static string InvalidateCacheIfSourceChanges {
            get {
                return ResourceManager.GetString("InvalidateCacheIfSourceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO error.
        /// </summary>
        internal static string IOError {
            get {
                return ResourceManager.GetString("IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cached data needs to be migrated to a newer format. Please wait while this happens....
        /// </summary>
        internal static string MigrationProgressMessage {
            get {
                return ResourceManager.GetString("MigrationProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6 Move.
        /// </summary>
        internal static string MoveButton {
            get {
                return ResourceManager.GetString("MoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * needs restart to apply changes.
        /// </summary>
        internal static string NeedsRestartToApplyChanges {
            get {
                return ResourceManager.GetString("NeedsRestartToApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7 New Folder.
        /// </summary>
        internal static string NewFolderButton {
            get {
                return ResourceManager.GetString("NewFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I would not like to participate.
        /// </summary>
        internal static string NoIWouldNotLikeToParticipate {
            get {
                return ResourceManager.GetString("NoIWouldNotLikeToParticipate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official GODspeed Facebook page.
        /// </summary>
        internal static string OfficialGODspeedFacebookpage {
            get {
                return ResourceManager.GetString("OfficialGODspeedFacebookpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official GODspeed website.
        /// </summary>
        internal static string OfficialGODspeedwebsite {
            get {
                return ResourceManager.GetString("OfficialGODspeedwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Profile.
        /// </summary>
        internal static string OpenProfile {
            get {
                return ResourceManager.GetString("OpenProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite all.
        /// </summary>
        internal static string OverwriteAll {
            get {
                return ResourceManager.GetString("OverwriteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite all older.
        /// </summary>
        internal static string OverwriteAllOlder {
            get {
                return ResourceManager.GetString("OverwriteAllOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially recognized game.
        /// </summary>
        internal static string PartiallyRecognizedGame {
            get {
                return ResourceManager.GetString("PartiallyRecognizedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Rebuilder.
        /// </summary>
        internal static string ProfileRebuilder {
            get {
                return ResourceManager.GetString("ProfileRebuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize Again.
        /// </summary>
        internal static string RecognizeAgain {
            get {
                return ResourceManager.GetString("RecognizeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized game.
        /// </summary>
        internal static string RecognizedGame {
            get {
                return ResourceManager.GetString("RecognizedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize Titles from Profile.
        /// </summary>
        internal static string RecognizeTitlesFromProfile {
            get {
                return ResourceManager.GetString("RecognizeTitlesFromProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Title.
        /// </summary>
        internal static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume all.
        /// </summary>
        internal static string ResumeAll {
            get {
                return ResourceManager.GetString("ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Thumbnail as....
        /// </summary>
        internal static string SaveThumbnailAs {
            get {
                return ResourceManager.GetString("SaveThumbnailAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Google.
        /// </summary>
        internal static string SearchGoogle {
            get {
                return ResourceManager.GetString("SearchGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session initiation failed.
        /// </summary>
        internal static string SessionInitiationFailed {
            get {
                return ResourceManager.GetString("SessionInitiationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip all.
        /// </summary>
        internal static string SkipAll {
            get {
                return ResourceManager.GetString("SkipAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this.
        /// </summary>
        internal static string SourceFileHeader {
            get {
                return ResourceManager.GetString("SourceFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string TargetFileHeader {
            get {
                return ResourceManager.GetString("TargetFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off Remote Copy and Continue.
        /// </summary>
        internal static string TurnOffRemoteCopyAndContinue {
            get {
                return ResourceManager.GetString("TurnOffRemoteCopyAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error occurred.
        /// </summary>
        internal static string UnhandledErrorOccurred {
            get {
                return ResourceManager.GetString("UnhandledErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Content.
        /// </summary>
        internal static string UnknownContent {
            get {
                return ResourceManager.GetString("UnknownContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized game.
        /// </summary>
        internal static string UnrecognizedGame {
            get {
                return ResourceManager.GetString("UnrecognizedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use jqe360.com for game recognition.
        /// </summary>
        internal static string UseJQE360 {
            get {
                return ResourceManager.GetString("UseJQE360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Passive Mode (Please note that XeXMenu doesn&apos;t support PASV!).
        /// </summary>
        internal static string UsePassiveMode {
            get {
                return ResourceManager.GetString("UsePassiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Remote Copy between NAS and FTP if able.
        /// </summary>
        internal static string UseRemoteCopy {
            get {
                return ResourceManager.GetString("UseRemoteCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Statistics Participation.
        /// </summary>
        internal static string UserStatisticsParticipation {
            get {
                return ResourceManager.GetString("UserStatisticsParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Help improve GODspeed&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Participate in its User Statistics and help improve the quality, reliability and performance of this software. If you choose to participate:&lt;/p&gt;
        ///&lt;div&gt;GODspeed will collect:&lt;/div&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Anonymous usage data&lt;/li&gt;
        ///    &lt;li&gt;Language settings&lt;/li&gt;
        ///    &lt;li&gt;System information (OS and .NET Framework version)&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;div&gt;But GODspeed will NOT:&lt;/div&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Collect your name, address or any other personal information&lt;/li&gt;
        ///    &lt;li&gt;Collect anything which [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserStatisticsParticipationContent {
            get {
                return ResourceManager.GetString("UserStatisticsParticipationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        internal static string WhatDoYouWantToDo {
            get {
                return ResourceManager.GetString("WhatDoYouWantToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 116.
        /// </summary>
        internal static string WriteErrorDialogButtonWidth {
            get {
                return ResourceManager.GetString("WriteErrorDialogButtonWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target already exists.
        /// </summary>
        internal static string WriteErrorDialogTitle {
            get {
                return ResourceManager.GetString("WriteErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Live Content.
        /// </summary>
        internal static string XboxLiveContent {
            get {
                return ResourceManager.GetString("XboxLiveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;m willing to participate (Recommended).
        /// </summary>
        internal static string YesImWillingToParticipate {
            get {
                return ResourceManager.GetString("YesImWillingToParticipate", resourceCulture);
            }
        }
    }
}
